version: '3'
services:
  postgres_db:
    container_name: 'postgres_db'
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: railway
